#!/bin/bash
# ۱. قفل کردن کلاینت‌های بدون حجم (قدیمی و جدید) یا تاریخ گذشته
sudo docker compose -f /home/qasem/radius-server/docker-compose.yml exec -T sas-radius-db mysql -u radius -pradpass -e "UPDATE radius.radcheck rc JOIN radius.dashboard_users du ON rc.username = du.username SET rc.value = CONCAT(du.password, '_EXPIRED') WHERE du.accountStatus != 'Active' OR (du.expiration IS NOT NULL AND du.expiration != 'Permanent' AND STR_TO_DATE(du.expiration, '%Y-%m-%d') < DATE(NOW())) OR (du.dataLimitBytes > 0 AND (SELECT COALESCE(SUM(acctinputoctets + acctoutputoctets), 0) FROM radius.radacct WHERE username = du.username) >= du.dataLimitBytes) OR (du.dataLimitBytes = 0 AND du.traffic = '0.00 MB');"

# ۲. باز کردن حساب کاربران فعال و دارای حجم
sudo docker compose -f /home/qasem/radius-server/docker-compose.yml exec -T sas-radius-db mysql -u radius -pradpass -e "UPDATE radius.radcheck rc JOIN radius.dashboard_users du ON rc.username = du.username SET rc.value = du.password WHERE du.accountStatus = 'Active' AND (du.expiration IS NULL OR du.expiration = 'Permanent' OR STR_TO_DATE(du.expiration, '%Y-%m-%d') >= DATE(NOW())) AND (du.dataLimitBytes > 0 AND (SELECT COALESCE(SUM(acctinputoctets + acctoutputoctets), 0) FROM radius.radacct WHERE username = du.username) < du.dataLimitBytes);"

# ۳. بستن اجباری سشن‌های باز کاربران غیرمجاز برای قطع اینترنت لایو
sudo docker compose -f /home/qasem/radius-server/docker-compose.yml exec -T sas-radius-db mysql -u radius -pradpass -e "UPDATE radius.radacct SET acctstoptime = NOW(), acctterminatecause = 'Session-Timeout' WHERE acctstoptime IS NULL AND username IN (SELECT username FROM radius.dashboard_users WHERE accountStatus != 'Active' OR (expiration IS NOT NULL AND expiration != 'Permanent' AND STR_TO_DATE(expiration, '%Y-%m-%d') < DATE(NOW())) OR (dataLimitBytes > 0 AND (SELECT COALESCE(SUM(acctinputoctets + acctoutputoctets), 0) FROM radius.radacct WHERE username = dashboard_users.username) >= dataLimitBytes) OR (dataLimitBytes = 0 AND traffic = '0.00 MB'));"
