sql {
    driver = "rlm_sql_mysql"
    dialect = "mysql"
    server = "sas-radius-db"
    port = 3306
    login = "radius"
    password = "radpass"
    radius_db = "radius"
    
    read_clients = yes
    client_table = "nas"

    group_attribute = "SQL-Group"

    acct_table1 = "radacct"
    acct_table2 = "radacct"
    postauth_table = "radpostauth"
    authcheck_table = "radcheck"
    authreply_table = "radreply"
    groupcheck_table = "radgroupcheck"
    groupreply_table = "radgroupreply"
    usergroup_table = "radusergroup"

    sql_user_name = "%{User-Name}"
    default_user_profile = ""

    query_on_not_found = no
    
    pool {
        start = 5
        min = 4
        max = 50
        spare = 3
        uses = 0
        retry_delay = 30
        lifetime = 0
        idle_timeout = 60
    }

    $INCLUDE ${modconfdir}/${.:name}/main/${dialect}/queries.conf
}
